<?php

declare(strict_types=1);

namespace App\Services\Ai;

use App\Services\Ai\Input\DnsCheckFailure;
use App\Services\Ai\Result\AnomalyExplanationResult;
use App\Services\Ai\Result\OnDemandExplanationResult;
use App\Services\Ai\Result\RemediationResult;
use App\Services\Ai\Result\SenderLabelResult;
use App\Services\Ai\Result\WeeklyDigestResult;
use Ramsey\Uuid\UuidInterface;

/**
 * Stub launch implementation (DEC-057): every method returns honest
 * placeholder copy explaining that AI is being prepared. Swap-out for
 * `AnthropicAiInsightsService` is a single line in `config/services.php`.
 *
 * Method parameters are intentionally unused — the stub doesn't introspect
 * any per-team / per-report context. The interface contract is what gets
 * tested against, not the canned strings.
 */
final readonly class StubAiInsightsService implements AiInsightsService
{
    private const string PLACEHOLDER_BLURB = 'AI Insights is being prepared — your account is ready. Once we flip the switch, this will be a plain-English explanation generated by Claude.';

    public function generateWeeklyDigest(UuidInterface $teamId): WeeklyDigestResult
    {
        return new WeeklyDigestResult(
            summaryMarkdown: '**AI Insights is being prepared.** Your account is ready — once we flip the switch, you will see a plain-English summary of your week\'s deliverability here.',
            keyMetrics: [],
            recommendations: [],
        );
    }

    public function explainAnomaly(UuidInterface $reportId, UuidInterface $teamId): AnomalyExplanationResult
    {
        return new AnomalyExplanationResult(
            explanation: self::PLACEHOLDER_BLURB,
            severity: 'info',
            recommendedAction: 'No action needed — AI explanations will arrive once AI Insights ships.',
        );
    }

    public function explainReport(UuidInterface $reportId, UuidInterface $teamId): OnDemandExplanationResult
    {
        return new OnDemandExplanationResult(
            explanation: self::PLACEHOLDER_BLURB,
        );
    }

    public function generateRemediationGuidance(UuidInterface $domainId, DnsCheckFailure $failure): RemediationResult
    {
        return new RemediationResult(
            instructionsMarkdown: self::PLACEHOLDER_BLURB,
            suggestedDnsRecords: [],
        );
    }

    public function labelSender(string $ip, string $domain): SenderLabelResult
    {
        return new SenderLabelResult(
            label: 'Unlabeled sender',
            confidence: 0.0,
        );
    }
}
